import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { AuthProvider } from "@/lib/AuthContext";
import { ApiProvider } from "@/lib/ApiProvider";
import { ProductSelectionProvider } from "@/lib/productSelection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full overflow-x-hidden">
        <ApiProvider>
          <AuthProvider>
            <Header />
            <ProductSelectionProvider>
              <div style={{ paddingTop: "var(--app-header-height, 120px)" }}>
                {children}
              </div>
            </ProductSelectionProvider>
          </AuthProvider>
        </ApiProvider>
      </body>
    </html>
  );
}
